import { Link, useParams } from 'react-router-dom';
import { CAREER_PROFILES } from '../data/careers';
import { BASE_TALENTS } from '../data/talents';
import { saveExperiment, useAppState } from '../services';
import { careerMatchReasons, dimensionLabels, entryDistanceLabel, formatFitIndex, formatScore } from '../utils';

export function CareerDetailPage() {
  const { careerId } = useParams();
  const state = useAppState();
  const career = CAREER_PROFILES.find((item) => item.id === careerId);
  const match = state.careerResults?.matches.find((item) => item.careerId === careerId);
  const saved = state.experiments.some((item) => item.careerId === careerId);
  if (!career) return <main className="mx-auto max-w-2xl px-5 py-24"><h1 className="text-4xl font-semibold">找不到這份工作</h1><Link to="/careers" className="mt-5 inline-block underline">回到職涯列表</Link></main>;
  return <main><header className="bg-slate-950 text-white"><div className="mx-auto max-w-7xl px-5 py-14 sm:py-20"><Link to="/careers" className="text-sm text-slate-400">← Career Matches</Link><div className="mt-8 grid gap-10 md:grid-cols-[1fr_auto]"><div><p className="text-sm font-bold tracking-widest text-blue-200 uppercase">{career.family.replaceAll('_', ' ')}</p><h1 className="mt-3 text-5xl font-semibold sm:text-7xl">{career.titleZh}</h1><p className="mt-2 text-xl text-slate-400">{career.titleEn}</p><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-300">{career.description}</p></div>{match && <div className="grid size-32 place-items-center rounded-full border-8 border-blue-200 bg-white text-center text-slate-950"><span><strong className="block text-2xl">{formatFitIndex(match.matchScore)}</strong><small>Career Fit Index</small></span></div>}</div></div></header>
    <div className="mx-auto max-w-7xl space-y-16 px-5 py-14">
      <section className="grid gap-6 md:grid-cols-2"><Info title="這份工作在做什麼"><p>{career.description}</p></Info><Info title="常見任務"><ul className="space-y-2">{career.coreTasks.map((task) => <li key={task}>• {task}</li>)}</ul></Info></section>
      {match ? <><section><h2 className="text-3xl font-semibold">為什麼推薦給你</h2><div className="mt-6 grid gap-4 md:grid-cols-3">{careerMatchReasons(match).map((reason) => <div key={reason} className="rounded-3xl bg-blue-50 p-6">{reason}</div>)}</div><p className="mt-4 text-sm text-slate-500">Confidence · {match.confidence} · Supporting evidence {match.supportingEvidenceIds.length} items</p></section><section><h2 className="text-3xl font-semibold">你哪些能力會用到</h2><div className="mt-6 flex flex-wrap gap-3">{Object.entries(career.talentRequirements).sort(([, a], [, b]) => (b ?? 0) - (a ?? 0)).slice(0, 8).map(([id, score]) => <span key={id} className="rounded-full bg-white px-4 py-2 shadow-sm">{BASE_TALENTS.find((item) => item.id === id)?.nameZh} · {formatScore(score ?? 0)}</span>)}</div></section></> : <p className="rounded-3xl bg-blue-50 p-6">完成 assessment 後，這裡會顯示個人化推薦原因。</p>}
      <section className="grid gap-6 lg:grid-cols-3"><Info title="工作環境">{Object.entries(career.environmentProfile).map(([key, value]) => <div key={key} className="mb-3"><div className="flex justify-between text-sm"><span>{dimensionLabels[key] ?? key}</span><span>{formatScore(value)}</span></div><div className="mt-1 h-2 rounded-full bg-slate-100"><div className="h-full rounded-full bg-slate-800" style={{ width: `${value * 100}%` }} /></div></div>)}</Info><Info title="可能喜歡"><ul className="space-y-2">{(match?.interestReasons.length ? match.interestReasons : career.coreTasks.slice(0, 3)).map((item) => <li key={item}>+ {item}</li>)}</ul></Info><Info title="可能消耗"><ul className="space-y-2 text-slate-700">{(match?.potentialFrictions.length ? match.potentialFrictions : ['尚無個人化摩擦資訊']).map((item) => <li key={item}>– {item}</li>)}</ul></Info></section>
      <section className="grid gap-6 md:grid-cols-2"><Info title="需要哪些技能"><ul className="space-y-3">{career.skills.sort((a, b) => b.importance - a.importance).map((skill) => <li key={skill.id} className="flex justify-between gap-4"><span>{skill.name}</span><span className="text-slate-400">{formatScore(skill.importance)}</span></li>)}</ul></Info><Info title="Entry Distance"><p className="text-3xl font-semibold">{match ? entryDistanceLabel[match.entryDistance.level] : entryDistanceLabel[career.entryBarrier]}</p><ul className="mt-5 space-y-2 text-sm text-slate-600">{match?.entryDistance.reasons.map((reason) => <li key={reason}>• {reason}</li>) ?? <li>完成 assessment 後計算個人進入距離。</li>}</ul></Info></section>
      <section className="rounded-[2rem] bg-blue-100 p-7 sm:p-10"><p className="text-sm font-bold tracking-widest text-slate-700 uppercase">Career Experiment · {career.careerExperiment.estimatedHours} 小時</p><h2 className="mt-3 text-3xl font-semibold">{career.careerExperiment.title}</h2><p className="mt-4 max-w-3xl leading-7">{career.careerExperiment.description}</p><div className="mt-5 flex flex-wrap gap-2">{career.careerExperiment.evidenceToCollect.map((item) => <span key={item} className="rounded-full bg-white/60 px-3 py-1 text-sm">觀察：{item}</span>)}</div><button type="button" onClick={() => saveExperiment({ careerId: career.id, status: 'saved', updatedAt: new Date().toISOString() })} className="mt-7 rounded-full bg-slate-950 px-6 py-3 font-semibold text-white">{saved ? '已加入我的實驗' : '加入我的實驗'}</button></section>
    </div>
  </main>;
}

function Info({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-3xl bg-white p-6"><h2 className="mb-5 text-2xl font-semibold">{title}</h2><div className="leading-7 text-slate-600">{children}</div></section>; }
