import { Link } from 'react-router-dom';
import { CAREER_PROFILES } from '../data/careers';
import { saveExperiment, useAppState } from '../services';

export function ExperimentsPage() {
  const state = useAppState();
  const suggestions = state.careerResults?.matches.slice(0, 6) ?? [];
  return <main className="mx-auto max-w-6xl px-5 py-14"><header className="max-w-3xl"><h1 className="text-5xl font-semibold">Career Experiments</h1><p className="mt-4 text-lg text-slate-600">推薦不是結論。用數小時的低風險行動，收集你在真實任務中的證據。</p></header><section className="mt-12"><h2 className="text-2xl font-semibold">我的實驗</h2>{state.experiments.length ? <div className="mt-5 grid gap-4 md:grid-cols-2">{state.experiments.map((record) => { const career = CAREER_PROFILES.find((item) => item.id === record.careerId); if (!career) return null; return <article key={record.careerId} className="rounded-3xl bg-white p-6"><p className="text-sm text-slate-500">{record.status.replaceAll('_', ' ')}</p><h3 className="mt-2 text-xl font-semibold">{career.careerExperiment.title}</h3><p className="mt-3 text-sm text-slate-600">{career.titleZh} · {career.careerExperiment.estimatedHours} 小時</p><div className="mt-5 flex gap-2"><button type="button" onClick={() => saveExperiment({ ...record, status: 'in_progress', updatedAt: new Date().toISOString() })} className="rounded-full bg-slate-950 px-4 py-2 text-sm text-white">開始</button><button type="button" onClick={() => saveExperiment({ ...record, status: 'completed', updatedAt: new Date().toISOString() })} className="rounded-full bg-blue-100 px-4 py-2 text-sm">完成</button><Link to={`/career/${career.id}`} className="px-3 py-2 text-sm underline">查看</Link></div></article>; })}</div> : <p className="mt-5 rounded-3xl border border-dashed border-slate-300 p-6 text-slate-600">尚未加入實驗。從職涯詳情頁選一個最想驗證的方向。</p>}</section><section className="mt-16"><h2 className="text-2xl font-semibold">根據結果建議</h2><div className="mt-5 grid gap-4 md:grid-cols-3">{suggestions.map((match) => { const career = CAREER_PROFILES.find((item) => item.id === match.careerId)!; return <Link key={match.careerId} to={`/career/${match.careerId}`} className="rounded-3xl bg-blue-100 p-6"><p className="text-sm text-slate-700">{career.careerExperiment.estimatedHours} 小時</p><h3 className="mt-2 text-xl font-semibold">{career.careerExperiment.title}</h3><p className="mt-3 text-sm text-slate-600">驗證 {career.titleZh}</p></Link>; })}</div>{!suggestions.length && <Link to="/assessment" className="mt-5 inline-block underline">先完成測驗取得建議</Link>}</section></main>;
}
