export function MethodologyPage() {
  const formula = [['Talent Match', '35%'], ['Interest Match', '18%'], ['Work Style Match', '15%'], ['Environment Match', '15%'], ['Values Match', '10%'], ['Transferable Skills', '7%']];
  return <main className="mx-auto max-w-5xl px-5 py-14"><header className="max-w-3xl"><p className="text-sm font-bold tracking-widest text-slate-600 uppercase">Methodology</p><h1 className="mt-4 text-5xl font-semibold">可重現、可解釋，不用 AI 猜分數。</h1><p className="mt-5 text-lg leading-8 text-slate-600">相同答案會產生相同結果。核心評分不使用生成式 AI，也不以星座、MBTI 或血型決定職涯方向。</p></header><div className="mt-12 grid gap-5 md:grid-cols-2">
    <section className="rounded-3xl bg-white p-7"><h2 className="text-2xl font-semibold">Career Fit 是相對吻合指數</h2><div className="mt-6 space-y-3">{formula.map(([label, weight]) => <div key={label} className="flex justify-between border-b border-slate-100 pb-3"><span>{label}</span><strong>{weight}</strong></div>)}</div><p className="mt-5 text-sm leading-6 text-slate-500">Career Fit 用來比較現有職業資料與目前 profile 的結構重疊。正式 validation 的 median 約 34.9、P90 約 45，因此 40 不是「只有 40% 適合」。它不是成功機率、錄取機率、能力百分比、適合度百分比或考試分數，也不包含市場熱度、薪資與職缺數。</p></section>
    <section className="rounded-3xl bg-slate-950 p-7 text-white"><h2 className="text-2xl font-semibold">Talent、Interest 與 Energy</h2><p className="mt-5 leading-7 text-slate-300">Talent 看你在不同情境中如何處理事情；Interest 看你願意靠近哪類問題。喜歡不等於已經擅長，擅長也不代表喜歡。</p><p className="mt-4 text-sm leading-6 text-slate-400">Energy 另外記錄使用某項能力後的投入或消耗。一個人可能很會溝通，但高密度溝通仍會耗能；系統不會因此抹除能力分數。</p></section>
    <section className="rounded-3xl bg-blue-50 p-7"><h2 className="text-2xl font-semibold">Evidence 與 Confidence</h2><p className="mt-4 leading-7 text-slate-600">能力訊號必須能追溯到題目與所選回答。Confidence 同時考慮題目涵蓋、不同題型的一致性與證據品質，只輸出 Low、Medium、High；填完全部題目不會自動得到 High。</p><h3 className="mt-6 font-semibold">Independent Signal</h3><p className="mt-2 text-sm leading-6 text-slate-600">一個獨立能力訊號，是不同問題中的一次判斷情境。相同題目的不同選項不會被當成多個獨立訊號。每個 Base Talent 由三個不同問題、三種題型交叉觀察。</p></section>
    <section className="rounded-3xl bg-blue-100 p-7"><h2 className="text-2xl font-semibold">Environment 與 Entry Distance</h2><p className="mt-4 leading-7 text-slate-600">環境分數比較工作要求與你的容忍度。當要求高於容忍度時，懲罰比一般偏好差異更強，但單一摩擦不會抹掉其他高度吻合。</p><p className="mt-4 text-sm leading-6 text-slate-600">Entry Distance 獨立計算教育、技能、經驗、證照、作品集、語言與專業執照。Fit 高、距離高仍可保留，意思是方向可能吻合，但需要較長準備。</p></section>
    <section className="rounded-3xl bg-white p-7"><h2 className="text-2xl font-semibold">你可能沒想過的方向</h2><p className="mt-4 leading-7 text-slate-600">這類結果必須通過既有的意外方向規則、不是你已考慮的職業或職涯類別，並避免和主要方向重複。只有真的存在結果時才顯示，不會出現空分類。</p></section>
    <section className="rounded-3xl bg-white p-7"><h2 className="text-2xl font-semibold">如何使用結果</h2><p className="mt-4 leading-7 text-slate-600">把結果當作可驗證的假設，而不是對你的定義。職涯會受經驗、機會、健康、照顧責任與市場條件影響；用 20 分鐘職涯體驗接觸真實任務，再以新證據修正判斷。</p><p className="mt-4 text-sm leading-6 text-slate-500">目前 Career Library 收錄 60 個職業。推薦只是在這個範圍內找出較吻合的方向；沒有出現在結果中，不代表你不適合。職涯世界遠比目前資料庫更廣。</p></section>
  </div></main>;
}
