import { useState } from 'react';
import { Link } from 'react-router-dom';
import { CareerCard } from '../components';
import { BASE_TALENTS, COMPOSITE_TALENTS } from '../data/talents';
import { CAREER_PROFILES } from '../data/careers';
import { buildBetaFeedbackExport, buildDiagnosticReport, downloadJson, saveCareerFeedback, saveOptionalComment, saveOverallFeedback, saveSurpriseFeedback, saveTalentFeedback, useAppState } from '../services';
import type { CareerFeedbackChoice, OverallFeedbackChoice, SurpriseFeedbackChoice, TalentAgreementChoice, TalentDiscoveryChoice } from '../types';
import { dimensionLabels, formatScore } from '../utils';

const sectionTitle = (number: string, title: string) => <div className="mb-6 flex items-baseline gap-4"><span className="text-sm font-bold text-slate-600">{number}</span><h2 className="text-2xl font-semibold sm:text-3xl">{title}</h2></div>;
const overallOptions: Array<[OverallFeedbackChoice, string]> = [
  ['clearer_direction', '比原本更知道自己可以往哪裡走'], ['discovered_abilities', '有發現一些以前沒注意過的能力'],
  ['useful_but_unclear', '有一些有用，但方向還是不太清楚'], ['very_different_from_self', '結果和我認識的自己差很多'],
  ['hard_to_understand', '我看不太懂這份結果'],
];
const agreementOptions: Array<[TalentAgreementChoice, string]> = [['strongly_agree', '很符合'], ['mostly_agree', '大致符合'], ['unsure', '不確定'], ['mostly_disagree', '不太符合']];
const discoveryOptions: Array<[TalentDiscoveryChoice, string]> = [['already_knew', '我本來就知道'], ['felt_it_not_named', '有感覺，但沒想過這可以算一種能力'], ['new_discovery', '這是新的發現'], ['disagree', '我不同意這個判斷']];

export function ResultsPage() {
  const state = useAppState();
  const { talentProfile, careerResults } = state;
  const [comment, setComment] = useState(state.betaFeedback.optionalComment ?? '');
  if (!talentProfile || !careerResults) return <main className="mx-auto max-w-3xl px-5 py-24 text-center"><h1 className="text-4xl font-semibold">還沒有可顯示的結果</h1><p className="mt-4 text-slate-600">完成探索題目後，這裡會呈現天賦、環境與職涯匹配。</p><Link to="/assessment" className="mt-8 inline-block rounded-full bg-slate-950 px-6 py-3 font-semibold text-white">前往測驗</Link></main>;
  const sortedTalents = [...talentProfile.baseTalents].sort((a, b) => b.score - a.score);
  const qualifiedStrengths = sortedTalents.filter((item) => ['natural_strength', 'developed_strength', 'emerging_potential'].includes(item.status));
  const strengths = (qualifiedStrengths.length ? qualifiedStrengths : sortedTalents).slice(0, 5);
  const composites = [...talentProfile.compositeTalents].sort((a, b) => b.score - a.score).slice(0, 4);
  const topWork = Object.entries(careerResults.profiles.workStyle).sort(([, a], [, b]) => b - a).slice(0, 3);
  const topInterest = Object.entries(careerResults.profiles.interestProfile).sort(([, a], [, b]) => b - a).slice(0, 2);
  const environments = Object.entries(careerResults.profiles.environmentTolerance).sort(([, a], [, b]) => b - a).slice(0, 4);
  const drains = sortedTalents.filter((item) => item.energyScore !== null && item.energyScore < 0).slice(0, 4);
  const experiments = careerResults.matches.slice(0, 3);
  const careerMatches = careerResults.categories.best_fit.length ? careerResults.categories.best_fit : careerResults.matches.slice(0, 4);

  return <main className="mx-auto max-w-7xl px-5 py-12 sm:py-20">
    <header className="max-w-3xl"><p className="text-sm font-bold tracking-[.2em] text-slate-600 uppercase">Your Discovery Map · Beta</p><h1 className="mt-4 text-4xl font-semibold tracking-tight sm:text-6xl">你不是一個職稱，你是一組可以被運用的工作模式。</h1><p className="mt-5 text-lg leading-8 text-slate-600">先理解你如何思考、與人互動和推進事情，再看哪些工作能承接這些模式。Career Fit Index 是相對排序指標，不是考試分數或成功機率。</p></header>
    <div className="mt-16 space-y-20">
      <section>{sectionTitle('01', '你的工作模式')}<div className="grid gap-4 md:grid-cols-2"><div className="rounded-3xl bg-slate-950 p-7 text-white"><p className="text-sm text-slate-400">自然偏好的工作方式</p><div className="mt-5 flex flex-wrap gap-3">{topWork.map(([key, score]) => <span key={key} className="rounded-full bg-white/10 px-4 py-2">{dimensionLabels[key] ?? key} · {formatScore(score)}</span>)}</div></div><div className="rounded-3xl bg-blue-100 p-7"><p className="text-sm text-slate-700">容易投入的問題類型</p><div className="mt-5 space-y-3">{topInterest.map(([key, score]) => <p key={key} className="text-xl font-semibold">{dimensionLabels[key] ?? key} <span className="text-sm font-normal text-slate-500">{formatScore(score)}</span></p>)}</div></div></div></section>
      <section>{sectionTitle('02', '自然優勢')}<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{strengths.map((item) => { const definition = BASE_TALENTS.find(({ id }) => id === item.talentId)!; return <article key={item.talentId} className="rounded-3xl bg-white p-6"><div className="flex justify-between"><span className="text-sm text-slate-500">{definition.category}</span><strong>{formatScore(item.score)}</strong></div><h3 className="mt-4 text-xl font-semibold">{definition.nameZh}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{definition.description}</p></article>; })}</div><Link to="/talents" className="mt-5 inline-block font-semibold underline decoration-blue-300 decoration-2 underline-offset-4">查看完整 Talent Landscape →</Link></section>
      <section>{sectionTitle('03', '你可能沒發現的天賦')}<div className="grid gap-4 md:grid-cols-2">{composites.map((item) => { const definition = COMPOSITE_TALENTS.find(({ id }) => id === item.compositeTalentId)!; const feedback = state.betaFeedback.talentFeedback.find(({ compositeTalentId }) => compositeTalentId === item.compositeTalentId); return <article key={item.compositeTalentId} className="rounded-3xl border border-slate-900/10 bg-white p-6"><p className="text-sm text-slate-500">Composite Talent · {formatScore(item.score)}</p><h3 className="mt-2 text-2xl font-semibold">{definition.nameZh}</h3><p className="mt-3 text-slate-600">{definition.shortDescription}</p><div className="mt-4 flex flex-wrap gap-2">{definition.components.map((id) => <span key={id} className="rounded-full bg-slate-100 px-3 py-1 text-xs">{BASE_TALENTS.find((talent) => talent.id === id)?.nameZh}</span>)}</div><div className="mt-6 border-t border-slate-100 pt-5"><p className="text-sm font-semibold">這項描述符合你嗎？</p><div className="mt-2 flex flex-wrap gap-2">{agreementOptions.map(([value, label]) => <button key={value} type="button" aria-pressed={feedback?.agreement === value} onClick={() => saveTalentFeedback(item.compositeTalentId, { agreement: value })} className={`rounded-full border px-3 py-2 text-xs ${feedback?.agreement === value ? 'border-ink bg-ink text-white' : 'border-ink/15'}`}>{label}</button>)}</div><p className="mt-4 text-sm font-semibold">這是你以前就知道的優勢嗎？</p><div className="mt-2 flex flex-wrap gap-2">{discoveryOptions.map(([value, label]) => <button key={value} type="button" aria-pressed={feedback?.discovery === value} onClick={() => saveTalentFeedback(item.compositeTalentId, { discovery: value })} className={`rounded-full border px-3 py-2 text-left text-xs ${feedback?.discovery === value ? 'border-ink bg-ink text-white' : 'border-ink/15'}`}>{label}</button>)}</div></div></article>; })}</div></section>
      <section>{sectionTitle('04', '適合發揮的環境')}<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{environments.map(([key, score]) => <div key={key} className="rounded-3xl bg-blue-50 p-6"><p className="font-semibold">{dimensionLabels[key] ?? key}</p><p className="mt-3 text-3xl font-semibold text-slate-700">{formatScore(score)}</p><p className="mt-2 text-xs text-slate-500">你的容忍／偏好訊號</p></div>)}</div></section>
      <section>{sectionTitle('05', '最符合你的幾個方向')}<p className="mb-5 max-w-3xl text-sm leading-6 text-slate-600">在目前收錄的 60 種職業中，以下方向與你的 Profile 重疊最高。前幾名通常很接近，排序不代表第一名是唯一答案；未出現的職業也不代表你不適合。</p>{careerResults.categories.best_fit.length === 0 && <p className="mb-5 rounded-3xl bg-white p-5 text-sm text-slate-600">目前沒有跨過 Best Fit 門檻；以下保留整體分數最接近的方向供你探索，不把它們冒充 Best Fit。</p>}<div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4">{careerMatches.map((match) => <CareerCard key={match.careerId} match={match} feedbackMode="career" feedbackValue={state.betaFeedback.careerFeedback.find(({ careerId }) => careerId === match.careerId)?.response} onFeedback={(value) => saveCareerFeedback(match.careerId, value as CareerFeedbackChoice)} />)}</div><Link to="/careers" className="mt-5 inline-block font-semibold underline decoration-blue-300 decoration-2 underline-offset-4">查看所有分類 →</Link></section>
      <section>{sectionTitle('06', 'Surprise Matches')}<div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4">{careerResults.categories.surprise_me.map((match) => <CareerCard key={match.careerId} match={match} feedbackMode="surprise" feedbackValue={state.betaFeedback.surpriseFeedback.find(({ careerId }) => careerId === match.careerId)?.response} onFeedback={(value) => saveSurpriseFeedback(match.careerId, value as SurpriseFeedbackChoice)} />)}</div>{careerResults.categories.surprise_me.length === 0 && <p className="rounded-3xl border border-dashed border-slate-300 p-6 text-slate-600">目前沒有足夠證據推薦明顯不同的方向。這是正常結果，不代表分析發生錯誤。</p>}</section>
      <section>{sectionTitle('07', '可能消耗你的模式')}<div className="grid gap-4 md:grid-cols-2">{drains.map((item) => { const definition = BASE_TALENTS.find(({ id }) => id === item.talentId)!; return <article key={item.talentId} className="rounded-3xl bg-slate-100 p-6"><h3 className="text-xl font-semibold">{definition.nameZh}</h3><p className="mt-2 text-sm text-slate-700">能力分數 {formatScore(item.score)}，但能量訊號 {item.energyScore?.toFixed(2)}。做得到不等於適合高密度使用。</p></article>; })}</div>{drains.length === 0 && <p className="text-slate-600">目前沒有足夠強的能量消耗訊號。</p>}</section>
      <section>{sectionTitle('08', 'Career Experiments')}<div className="grid gap-4 md:grid-cols-3">{experiments.map((match) => { const career = CAREER_PROFILES.find((item) => item.id === match.careerId); return <Link key={match.careerId} to={`/career/${match.careerId}`} className="rounded-3xl bg-blue-100 p-6 transition hover:-translate-y-1"><p className="text-sm text-slate-700">先小規模驗證</p><h3 className="mt-3 text-xl font-semibold">{career?.careerExperiment.title ?? career?.titleZh}</h3><p className="mt-4 text-sm font-semibold">查看實驗 →</p></Link>; })}</div><Link to="/experiments" className="mt-5 inline-block font-semibold underline decoration-blue-300 decoration-2 underline-offset-4">管理實驗 →</Link></section>
      <section className="rounded-[2rem] border border-ink/10 bg-white p-6 sm:p-9">{sectionTitle('09', '這份結果對你有幫助嗎？')}<p className="text-sm leading-6 text-slate-600">Feedback 用來改善題目、結果解釋與職業資料。目前所有回饋只保存在這台裝置的瀏覽器中，除非你主動匯出 JSON，否則不會送到任何 server。</p><h3 className="mt-7 text-lg font-semibold">看完這份結果，你比較接近哪種感覺？</h3><div className="mt-3 grid gap-2 sm:grid-cols-2">{overallOptions.map(([value, label]) => <button key={value} type="button" aria-pressed={state.betaFeedback.overallFeedback === value} onClick={() => saveOverallFeedback(value)} className={`rounded-2xl border p-3 text-left text-sm ${state.betaFeedback.overallFeedback === value ? 'border-ink bg-ink text-white' : 'border-ink/15 bg-white'}`}>{label}</button>)}</div><label className="mt-7 block text-sm font-semibold" htmlFor="beta-comment">還有什麼想讓我們知道？（選填）</label><textarea id="beta-comment" value={comment} maxLength={2000} onChange={(event) => setComment(event.target.value)} className="mt-2 min-h-28 w-full rounded-2xl border border-ink/15 bg-white p-4" placeholder="請避免填寫姓名、Email 或其他個人資料。" /><div className="mt-3 flex flex-wrap gap-3"><button type="button" onClick={() => saveOptionalComment(comment)} className="rounded-full bg-ink px-5 py-3 text-sm font-semibold text-white">保存留言</button><button type="button" onClick={() => downloadJson(`career-discovery-feedback-${state.sessionId}.json`, buildBetaFeedbackExport(state))} className="rounded-full border border-ink/15 px-5 py-3 text-sm font-semibold">匯出 Beta Feedback</button><button type="button" onClick={() => downloadJson(`career-discovery-diagnostic-${state.sessionId}.json`, buildDiagnosticReport(state))} className="rounded-full border border-ink/15 px-5 py-3 text-sm font-semibold">Export Diagnostic Report</button></div></section>
    </div>
  </main>;
}
