import type { CareerProfile, EducationLevel, EntryDistanceLevel } from '../types';

export const careerEntryBarrierLabel: Record<EntryDistanceLevel, string> = {
  low: '一般準備門檻較低',
  medium: '通常需要基礎訓練或相關經驗',
  high: '通常需要較完整的專業準備',
  very_high: '通常需要長期訓練或法定資格',
};

const educationLabel: Record<EducationLevel, string> = {
  none: '沒有特定學歷限制',
  secondary: '高中職或同等程度',
  certificate: '專業證書或職業訓練',
  associate: '專科或同等訓練',
  bachelor: '大學學位或同等專業能力',
  master: '碩士學位或同等進階訓練',
  doctorate: '博士學位或同等研究訓練',
};

const skillLabelsZh: Record<string, string> = {
  'Account planning': '客戶策略規劃',
  'Action planning': '行動規劃',
  'Aircraft systems': '飛機系統知識',
  'Assessment design': '評量設計',
  'Audience research': '受眾研究',
  'Audio editing': '音訊剪輯',
  'Audio storytelling': '聲音敘事',
  'Authoring tools': '數位教材製作工具',
  'Behavioral interviewing': '行為式面談',
  'Branching logic': '分支邏輯設計',
  'Brand positioning': '品牌定位',
  'Brand voice': '品牌語調',
  'Brief writing': '簡報摘要撰寫',
  'Budget analysis': '預算分析',
  'Business analysis': '商業分析',
  'Business cases': '商業案例評估',
  CAD: '電腦輔助設計（CAD）',
  'CRM administration': '顧客關係系統管理',
  'Campaign experiments': '行銷活動實驗',
  'Campaign planning': '行銷活動規劃',
  'Candidate sourcing': '人才尋訪',
  'Career assessment': '職涯評估',
  'Change facilitation': '變革引導',
  'Circuit diagnosis': '電路診斷',
  'Clinical documentation': '臨床紀錄',
  'Clinical protocol': '臨床試驗規範',
  'Clinical workflows': '臨床工作流程',
  'Coaching conversations': '教練式對談',
  'Concept writing': '概念文案撰寫',
  'Content planning': '內容規劃',
  'Control testing': '內控制度測試',
  'Conversion optimization': '轉換率優化',
  'Copy editing': '文字編輯',
  'Cost accounting': '成本會計',
  'Cultural research': '文化研究',
  'Data visualization': '資料視覺化',
  'Demand planning': '需求規劃',
  'Destination storytelling': '旅遊目的地敘事',
  'Dialogue writing': '對話撰寫',
  'Discovery calls': '需求探索訪談',
  'Disruption handling': '行程異常處理',
  Documentation: '文件撰寫與管理',
  ERP: '企業資源規劃系統（ERP）',
  'ESG frameworks': '環境、社會與治理框架（ESG）',
  'Editorial writing': '編輯寫作',
  'Electrical wiring': '電氣配線',
  'Emergency planning': '緊急應變規劃',
  'Employee lifecycle operations': '員工全週期作業',
  'Engineering mechanics': '工程力學',
  'Environmental sampling': '環境採樣',
  'Executive communication': '高階溝通',
  'Experience design': '體驗設計',
  'Experiment analysis': '實驗分析',
  'Fabrication coordination': '製作協調',
  Facilitation: '團體引導',
  'Fact checking': '事實查核',
  'Fault isolation': '故障定位',
  'Financial close': '財務結帳',
  'Financial modeling': '財務模型建置',
  'Functional assessment': '功能評估',
  GIS: '地理資訊系統（GIS）',
  'Guest relations': '賓客關係',
  HRIS: '人力資源資訊系統（HRIS）',
  'Health data standards': '健康資料標準',
  'Hiring coordination': '招募流程協調',
  'Hotel operations': '旅館營運',
  'Incident command': '事件指揮',
  'Incident response': '事件應變',
  'Informed consent': '知情同意程序',
  'Instructional content': '教學內容設計',
  'Interaction design': '互動設計',
  'Interactive narrative': '互動敘事',
  'Internal controls': '內部控制',
  'Interview production': '訪談製作',
  'Interview research': '訪談研究',
  Interviewing: '訪談技巧',
  'Inventory analysis': '庫存分析',
  'Itinerary design': '行程設計',
  'Knowledge management': '知識管理',
  'Leadership development': '領導力發展',
  'Lean improvement': '精實改善',
  'Learning analytics': '學習成效分析',
  'Learning design': '學習設計',
  'Learning needs analysis': '學習需求分析',
  'Literature review': '文獻回顧',
  'Machine setup': '機台設定',
  'Maintenance documentation': '維修文件紀錄',
  'Management reporting': '管理報表',
  'Market synthesis': '市場資訊整合',
  'Materiality assessment': '重大性評估',
  'Narrative strategy': '敘事策略',
  Negotiation: '協商談判',
  'Network fundamentals': '網路基礎',
  'News writing': '新聞寫作',
  'On-site troubleshooting': '現場問題排除',
  'Operational metrics': '營運指標',
  'Organization diagnosis': '組織診斷',
  'Outcome tracking': '成果追蹤',
  'Participant operations': '研究參與者作業',
  'Partnership development': '合作夥伴開發',
  'Pipeline management': '業務管線管理',
  'Policy administration': '政策制度執行',
  'Policy analysis': '政策分析',
  'Post-production workflow': '後期製作流程',
  'Precision measurement': '精密量測',
  'Problem structuring': '問題結構化',
  'Process analysis': '流程分析',
  'Process mapping': '流程盤點',
  'Product adoption': '產品導入推動',
  'Product analytics': '產品數據分析',
  'Product discovery': '產品需求探索',
  'Product metrics': '產品指標設計',
  'Program administration': '計畫行政管理',
  'Program design': '計畫設計',
  Programming: '程式開發',
  'Project delivery': '專案交付',
  'Project planning': '專案規劃',
  Prospecting: '潛在客戶開發',
  'Prototype testing': '原型測試',
  Prototyping: '原型製作',
  'Public budgeting': '公共預算規劃',
  'Public consultation': '公眾諮詢',
  'Regulatory compliance': '法規遵循',
  'Regulatory documentation': '法規文件撰寫',
  'Regulatory interpretation': '法規解讀',
  'Requirements mapping': '需求盤點',
  'Research governance': '研究治理',
  'Research synthesis': '研究整合',
  'Reservation systems': '訂位系統操作',
  'Risk assessment': '風險評估',
  'Risk communication': '風險溝通',
  'Risk management': '風險管理',
  Roadmapping: '發展路線規劃',
  'Run-of-show planning': '活動流程規劃',
  SQL: '資料庫查詢（SQL）',
  'Safety procedures': '安全作業程序',
  'Sales forecasting': '銷售預測',
  'Security monitoring': '資安監控',
  'Service blueprinting': '服務藍圖設計',
  'Service recovery': '服務補救',
  'Software testing': '軟體測試',
  'Solution demos': '解決方案展示',
  'Spatial design': '空間設計',
  'Spatial planning': '空間規劃',
  'Staff scheduling': '人力排班',
  'Stakeholder coordination': '關係人協調',
  'Stakeholder governance': '關係人治理',
  'Stakeholder management': '關係人管理',
  'Statistical quality': '統計品質管理',
  Statistics: '統計分析',
  'Study design': '研究設計',
  'Supplier negotiation': '供應商協商',
  'Survey design': '問卷設計',
  'Sustainability reporting': '永續報告撰寫',
  'System configuration': '系統設定',
  'System design': '系統設計',
  'System testing': '系統測試',
  'Systems mapping': '系統關係盤點',
  'Technical drawing': '技術製圖',
  'Technical drawings': '技術圖面判讀',
  'Technical storytelling': '技術內容轉譯',
  'Therapeutic activity': '治療活動設計',
  'Training evaluation': '訓練成效評估',
  'Travel costing': '旅遊成本估算',
  'Travel documentation': '旅遊文件作業',
  'Treatment systems': '處理系統操作',
  'Usability testing': '易用性測試',
  'User interviews': '使用者訪談',
  'Vendor coordination': '供應商協調',
  'Video editing': '影片剪輯',
  'Visual pacing': '視覺節奏控制',
  'Web analytics': '網站數據分析',
  'Webinar facilitation': '線上講座引導',
  'Workflow design': '工作流程設計',
  'Workshop facilitation': '工作坊引導',
};

export const skillNameLabel = (name: string) => skillLabelsZh[name] ?? name;

export function careerRequirementItems(career: CareerProfile): string[] {
  const requirements = career.entryRequirements;
  const items = [
    `學歷或訓練：${educationLabel[requirements.education]}`,
    requirements.yearsExperience > 0
      ? `相關經驗：通常約 ${requirements.yearsExperience} 年`
      : '相關經驗：可從入門任務開始累積',
    `核心技能：${career.skills.slice(0, 3).map(({ name }) => skillNameLabel(name)).join('、')}`,
  ];
  if (requirements.certifications.length) items.push(`證照：${requirements.certifications.join('、')}`);
  if (requirements.portfolio) items.push('作品集：通常需要能展示實作成果的作品');
  if (requirements.languages.length) items.push(`語言：${requirements.languages.join('、')}`);
  if (requirements.professionalLicenses.length) items.push(`專業執照：${requirements.professionalLicenses.join('、')}`);
  return items;
}

export function careerRequirementSummary(career: CareerProfile): string {
  return careerRequirementItems(career).slice(0, 2).join('；');
}
